---
name: RASPAP Base Image
version: dev
slug: raspap-base
description: Docker Debian base images used by Home Assistant Community Add-ons.
url: https://github.com/azenned/hassio-addon-raspapbase
arch:
  - aarch64
  - armhf
  - armv7
  - i386
